# Email Service Configuration
spring:
  application:
    name: email-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:flux_email_db}
    username: ${DB_USERNAME:flux_user}
    password: ${DB_PASSWORD:flux_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true

  # Mail Configuration
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 10000
    requested-heartbeat: 30

  # Redis Configuration
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes

  # Thymeleaf Configuration
  thymeleaf:
    cache: ${THYMELEAF_CACHE:true}
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

# Server Configuration
server:
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: /api/v1

# Management & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.flux.emailservice: ${LOG_LEVEL:INFO}
    org.springframework.mail: DEBUG
    org.springframework.amqp: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Custom Application Properties
app:
  email:
    # Sender Configuration
    from-address: ${EMAIL_FROM:noreply@flux.com}
    from-name: ${EMAIL_FROM_NAME:Flux Team}

    # Retry Configuration
    retry:
      max-attempts: ${EMAIL_RETRY_MAX:3}
      delay-ms: ${EMAIL_RETRY_DELAY:5000}
      backoff-multiplier: 2.0

    # Rate Limiting
    rate-limit:
      per-hour: ${EMAIL_RATE_LIMIT_HOUR:100}
      per-day: ${EMAIL_RATE_LIMIT_DAY:1000}

    # Processing Configuration
    batch-size: ${EMAIL_BATCH_SIZE:10}
    processing-interval-ms: ${EMAIL_PROCESSING_INTERVAL:30000}

    # Template Configuration
    template:
      cache-ttl-seconds: ${TEMPLATE_CACHE_TTL:3600}

    # Security Configuration
    security:
      blacklist-domains: ${EMAIL_BLACKLIST_DOMAINS:10minutemail.com,tempmail.org}
      whitelist-enabled: ${EMAIL_WHITELIST_ENABLED:false}
      whitelist-domains: ${EMAIL_WHITELIST_DOMAINS:}

---
# Development Profile
spring:
  config:
    activate:
      on-profile: development
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587

logging:
  level:
    com.flux.emailservice: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.flux.emailservice: WARN
    root: INFO
